# Site settings
title:          A Young Dreamer
description:    "Blog pribadi untuk berbagi seputar pengalaman hidup dan juga tentang hal-hal seputar Teknologi"
#baseurl:        "/tale"
url:            "https://mfaridzia.github.io"

# Author
author:
  name:         Muhammad Farid Zia
  url:          https://mfaridzia.github.io
  email:        muhfaridzia@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
